name = "cf-worker-linkshortener"
main = "build/worker/shim.mjs"
compatibility_date = "2022-11-28"

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install -q worker-build --version 0.0.8 && worker-build --release"

[[ d1_databases ]]
binding = "DB"
database_name = "REPLACE"
database_id = "REPLACE"
preview_database_id = "REPLACE"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
